//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagerData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string userPwd { get; set; }
        public byte userLevel { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
