//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagerData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterProductVariantSubAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterProductVariantSubAttribute()
        {
            this.ProductVariantAllocs = new HashSet<ProductVariantAlloc>();
        }
    
        public int id { get; set; }
        public int attributeId { get; set; }
        public string name { get; set; }
        public string subVariantDesc { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual MasterProductVariantAttribute MasterProductVariantAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariantAlloc> ProductVariantAllocs { get; set; }
    }
}
