//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagerData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMEntities : DbContext
    {
        public PMEntities()
            : base("name=PMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<MasterProductCategory> MasterProductCategories { get; set; }
        public virtual DbSet<MasterProductVariantAttribute> MasterProductVariantAttributes { get; set; }
        public virtual DbSet<MasterProductVariantSubAttribute> MasterProductVariantSubAttributes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCompositeAlloc> ProductCompositeAllocs { get; set; }
        public virtual DbSet<ProductCompositeLine> ProductCompositeLines { get; set; }
        public virtual DbSet<ProductVariantAlloc> ProductVariantAllocs { get; set; }
        public virtual DbSet<ProductStandardAlloc> ProductStandardAllocs { get; set; }
        public virtual DbSet<MasterProductType> MasterProductTypes { get; set; }
    }
}
