//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagerData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantAlloc
    {
        public int id { get; set; }
        public int prodId { get; set; }
        public int subAttrId { get; set; }
        public double price { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual MasterProductVariantSubAttribute MasterProductVariantSubAttribute { get; set; }
        public virtual Product Product { get; set; }
    }
}
